# set language
language: python

# requirements
install: 
  - pip install -r requirements.txt
  - python setup.py develop

matrix:
  include:
    # run pandasGEXpress python2_tests      
    - python: "2.7"
      script:
        - python -m unittest discover -p "test_*.py" -s cmapPy/pandasGEXpress/tests/python2_tests/

    # run pandasGEXpress python3_tests         
    - python: "3.6"
      script:
        - python -m unittest discover -p "test_*.py" -s cmapPy/pandasGEXpress/tests/python3_tests/
    
    # run set_io tests for python2    
    - python: "2.7"
      script:
        - python -m unittest discover -p "test_*.py" -s cmapPy/set_io/tests/

    # run set_io tests for python3    
    - python: "3.6"
      script:
        - python -m unittest discover -p "test_*.py" -s cmapPy/set_io/tests/
      
    # run math tests for python2
    - python: "2.7"
      script:
        - python -m unittest discover -p "test_*.py" -s cmapPy/math/tests/
    
     # run math tests for python3
    - python: "3.6"
      script:
        - python -m unittest discover -p "test_*.py" -s cmapPy/math/tests/

    # run python2_python3_comaptibility tests for python2      
    - python: "2.7"
      script:
        - python -m unittest discover -p "test_python2_python3_*.py" -s cmapPy/pandasGEXpress/tests/
   
    # run python2_python3_comaptibility tests for python3        
    - python: "3.6"
      script:
        - python -m unittest discover -p "test_python2_python3_*.py" -s cmapPy/pandasGEXpress/tests/

# what branches of github to use
branches:
  only:
    - master