language: python

# requirements
install: 
  - pip install -r requirements.txt
  - python setup.py develop

matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd cmapPy/pandasGEXpress/tests/python2_tests
      script:
        - python -m unittest discover -p "test_*.py"

    - language: python
      python: 3.5
      before_script:
        - cd cmapPy/pandasGEXpress/tests/python3_tests
      script:
        - python -m unittest discover -p "test_*.py"

    - language: python
      python: 2.7
      env:
        - TEST_DIR=cmapPy/math/tests
        - TEST_DIR=cmapPy/set_io/tests
      script:
        - cd $TEST_DIR && python -m unittest discover -p "test_*.py"
    
    - language: python
      python: 3.5
      env:
        - TEST_DIR=cmapPy/math/tests
        - TEST_DIR=cmapPy/set_io/tests
      script:
        - cd $TEST_DIR && python -m unittest discover -p "test_*.py"

    - language: python
      python: 2.7
      before_script:
        - cd cmapPy/pandasGEXpress/tests/
      script:
        - python -m unittest discover -p test_python2_python3_compatibility.py

    - language: python
      python: 3.5
      before_script:
        - cd cmapPy/pandasGEXpress/tests/
      script:
        - python -m unittest discover -p test_python2_python3_compatibility.py
     
# what branches of github to use
branches:
  only:
    - master
    - travis_testing
