language: python

# requirements
install: 
  - pip install -r requirements.txt
  - python setup.py develop

# environments to use for tests (below)
matrix:
        include:
                - python: "2.7"
                  env:
                          - TEST_DIR=cmapPy/pandasGEXpress/tests
                          - TEST_DIR=cmapPy/pandasGEXpress/tests/python2_tests
                          - TEST_DIR=cmapPy/set_io/tests
                          - TEST_DIR=cmapPy/math/tests
                  -python: "3.6"
                  env:
                          - TEST_DIR=cmapPy/pandasGEXpress/tests
                          - TEST_DIR=cmapPy/pandasGEXpress/tests/python3_tests
                          - TEST_DIR=cmapPy/set_io/tests
                          - TEST_DIR=cmapPy/math/tests

# run all tests in each test dir 
script: cd $TEST_DIR && python -m unittest discover -p "test_*.py"

# what branches of github to use
branches:
  only:
    - master
    - travis_testing
