language: python

# python versioning 
python:
  - 2.7

# requirements
install: 
  - pip install -r requirements.txt
  - python setup.py develop

# environments to use for tests (below)
env: 
  - TEST_DIR=cmapPy/pandasGEXpress/tests/python2_tests
  - IO_TEST_DIR=cmapPy/set_io/tests
  - MATH_TEST_DIR=cmapPy/math/tests

# run all tests in each test dir 
script:
  - cd $TEST_DIR && python -m unittest discover -p "test_*.py"
  - cd $IO_TEST_DIR && python -m unittest discover -p "test_*.py"
  - cd $MATH_TEST_DIR && python -m unittest discover -p "test_*.py"

# what branches of github to use
branches:
  only:
    - master
    - travis_testing
